apiVersion: v1
kind: Service
metadata:
  name: k8s-api-proxy
  labels:
    app: k8s-api-proxy
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: 'true'
spec:
  type: LoadBalancer
  loadBalancerIP: ${internal_loadbalancer_ip}
  ports:
    - port: 8443
      targetPort: 8118
      protocol: TCP
      name: http
  selector:
    app: k8s-api-proxy
